import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/common/header";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Gathergro",
  description: "Generated by create gathergro",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={montserrat.className}>
        <Header />
        {children}</body>
    </html>
  );
}
